### ISSUE TITLE
Panes always starts with size 50% in Vue 3

### ISSUE THREAD

**Issue by muhammeddemir** [antoniandre/splitpanes#108]
When the page loads for the first time, the panes do not obey the size property. 
I have to refresh the page every time.

"splitpanes": "^3.0.4",
"vue": "^3.0.0" (typescript)

![slitpanes](https://user-images.githubusercontent.com/23164910/101018286-54cefc00-357c-11eb-92c7-a7c33fe8db12.gif)

```
<template>
   
  <splitpanes class="default-theme" vertical style="height: 100vh;">
    <pane size="20" min-size="15" max-size="25">
      <div style="padding:30px;"><span>Contextual Navigation</span></div>
    </pane>
    <pane size="80">
      <div style="padding:30px;"><span>Editor</span></div>
    </pane>
  </splitpanes>
  
</template>

<script lang="ts">
import { Splitpanes, Pane } from 'splitpanes'
import 'splitpanes/dist/splitpanes.css'

export default {
  name: 'Editor',
  components: { Splitpanes, Pane }  
}
</script>
```

Do you have a solution for that?

**Comment by btassone** [comment]
I am running into the same issue

**Comment by jakenuts** [comment]
For reference, if the user modifies state (not just the pane size, anything), the panes animate to the initial value.

**Comment by pipe01** [comment]
I'm having the same issue, a workaround is to set the pane's size after mounting, like this:

```vue
<template lang="pug">
splitpanes.default-theme
    pane(:size="size") Pane 1
    pane(:size="100 - size") Pane 2
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from "vue"

export default defineComponent({
    setup() {
        const size = ref(0);

        onMounted(() => size.value = 20);

        return { size }
    }
})
</script>
```

**Comment by muhammeddemir** [comment]
Hello everyone, I think I've found an interim solution. 
Enter the numbers in such a way that it is never 100%. 
I solved with the size 99% panes.

**Example**
pane1 = 20%
pane2 = 79%

Not clean but it's works.

**Comment by cary-hu** [comment]
Bug still here, two panel display as 50% width, after a few time, the panel will auto scale to setted size.

**Comment by SimonMeissner** [comment]
I really like this library! Would also love to see this bug getting resolved :)
Also none of the solutions worked for me :(

**Comment by spacekong** [comment]
> Bug still here, two panel display as 50% width, after a few time, the panel will auto scale to setted size.

The bug still exists today in 2024

**Comment by danzhoua** [comment]
I meeted the same question in my vue3 project.My solution is add a loading indicator before the pane mounted,the loading time is setted about 200ms.so it‘s seemed ok,at least on the surface.

**Comment by muhammed8figures** [comment]
I would recommend everyone to use **PrimeVue Splitters**.
It works very well. 

https://primevue.org/splitter/

```
import Splitter from "primevue/splitter";
import SplitterPanel from "primevue/splitterpanel";
```

**Comment by muhammed-demir** [comment]
I would recommend everyone to use **PrimeVue Splitters**.
It works very well. 

https://primevue.org/splitter/

```
import Splitter from "primevue/splitter";
import SplitterPanel from "primevue/splitterpanel";
```

**Comment by White-Give** [comment]
<img width="531" alt="image" src="https://github.com/user-attachments/assets/555956bf-2456-4c37-b580-3a49db720518">
动态v-if显示pane时不会按照size去设置窗格大小，应该是一样的问题，初绘不按照size渲染

**Comment by White-Give** [comment]
> > Bug still here, two panel display as 50% width, after a few time, the panel will auto scale to setted size.
> 
> The bug still exists today in 2024
> 
> 
> > 错误仍然在这里，两个面板显示为50%的宽度，几次后，面板将自动缩放到设定的大小。
> 
> 2024年的今天，

I use nexttick to set the size after the page is drawn. You can set the size as a variable to try

**Comment by sytexa-julia** [comment]
Hoping this can be resolved with the upcoming updates!

**Comment by antoniandre** [comment]
Thanks for reporting [@muhammed-demir](https://github.com/muhammed-demir),
This is now fixed and released in version 4.1.2.

On the very first render, pane sizes weren't applied yet, causing the browser to distribute them equally (50/50) for a brief flash. Panes now use their given size immediately from the first paint.

Sorry for the long wait guys - better late than never ;)
